### ISSUE TITLE
Printing multiple tags on a single sheet

### ISSUE THREAD

**Issue by anushl9o5** [AprilRobotics/apriltag-generation#5]
Hey @mkrogius,
I am trying to print a group of tags (4) on a single sheet of paper, what is the best way to do this?
Currently, I am cropping the tag images and pasting multiple of them on a single common page, which is quite time-consuming in case you want a bunch of such tag groups.

Is there a way to modify the PostScript file, to do this, If so, please let me know how I can go about doing this?

Thanks

**Comment by mkrogius** [comment]
We  don't offer any solutions for putting multiple tags together, but if you come up with something, feel free to post it on here.

**Comment by yusufguleray** [comment]
You can use the image magick software to tile multiple images together into one single image. Then you can print this image on a paper.
`magick montage -tile 2x2`
