### ISSUE TITLE
Port tags from other packages

### ISSUE THREAD

**Issue by swiz23** [AprilRobotics/apriltag-generation#6]
A bit of a noob question, but is it possible to make AR tags from other AR-tag tracking packages work with apriltag_ros?

For example - could the AR tags below from the ar_track_alvar package be made to work with apriltag_ros?

![image](https://user-images.githubusercontent.com/31753673/102541558-29690880-4076-11eb-9b20-857c400bc21e.png)

I know I could just use their repo to do tag tracking, but as it doesn't seem to be actively maintained, and I'd like my robot to work in ROS Noetic (which doesn't seem to be currently supported there but is supported by apriltag_ros), I want to use apriltag_ros.

**Comment by acshi** [comment]
Just to close this issue, that is not possible because the detectors work in fundamentally different ways, (well except for maybe that they both detect a square border to start with.)
