### ISSUE TITLE
How to distinguish between April Tag versions 1, 2 and 3?

### ISSUE THREAD

**Issue by yusufguleray** [AprilRobotics/apriltag-generation#8]
It is said in the main repo that "Most recent version of AprilTag, AprilTag 3, which includes a faster (>2x) detector, improved detection rate on small tags, flexible tag layouts, and pose estimation." but it is not defined which tag family corresponds to the AprilTag 3. 

Is only the  `standard_x `  library (e.g. `tagStandard41h12`) part of the AprilTag 3 or other libraries such as `classic_x` or `circle_x` also work with the AprilTag 3's fast and improved algorithm?

Thanks in advance!

**Comment by acshi** [comment]
These improvements to tag detection are compatible with all the older tag
styles! So you get the benefits by using the newer library without changing
which tags you use. AprilTag3 additionally supports some new styles that
move the detection border inward.

**Comment by yusufguleray** [comment]
That sounds great. Thanks a lot, Acshi!
